server:
  port: 8888

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
    discovery:
      service-id: Gateway

  application:
    name: Gateway

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
