server:
  port: 8082

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
    discovery:
      service-id: SERVICE-CAR

  application:
    name: SERVICE-CAR

  datasource:
    url: jdbc:mysql://localhost:3306/carservicedb?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
